/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#include "remoteattestation_u.h"

#include <openenclave/edger8r/host.h>

OE_EXTERNC_BEGIN

/**** ECALL function wrappers. ****/

oe_result_t get_remote_report_with_pubkey(
    oe_enclave_t* enclave,
    int* _retval,
    uint8_t** pem_key,
    size_t* key_size,
    uint8_t** remote_report,
    size_t* remote_report_size)
{
    oe_result_t _result = OE_FAILURE;

    /* Marshalling struct. */
    get_remote_report_with_pubkey_args_t _args, *_pargs_in = NULL, *_pargs_out = NULL;

    /* Marshalling buffer and sizes. */
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Deep copy buffer. */
    /* No pointers to save for deep copy. */

    /* Fill marshalling struct. */
    memset(&_args, 0, sizeof(_args));
    _args.pem_key = (uint8_t**)pem_key;
    _args.key_size = (size_t*)key_size;
    _args.remote_report = (uint8_t**)remote_report;
    _args.remote_report_size = (size_t*)remote_report_size;

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(get_remote_report_with_pubkey_args_t));
    /* There were no corresponding parameters. */
    
    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(get_remote_report_with_pubkey_args_t));
    if (pem_key)
        OE_ADD_SIZE(_output_buffer_size, sizeof(uint8_t*));
    if (key_size)
        OE_ADD_SIZE(_output_buffer_size, sizeof(size_t));
    if (remote_report)
        OE_ADD_SIZE(_output_buffer_size, sizeof(uint8_t*));
    if (remote_report_size)
        OE_ADD_SIZE(_output_buffer_size, sizeof(size_t));
    
    /* Allocate marshalling buffer. */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);
    _buffer = (uint8_t*)oe_malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL)
    {
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }
    
    /* Serialize buffer inputs (in and in-out parameters). */
    _pargs_in = (get_remote_report_with_pubkey_args_t*)_input_buffer;
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));
    /* There were no in nor in-out parameters. */
    
    /* Copy args structure (now filled) to input buffer. */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call enclave function. */
    if ((_result = oe_call_enclave_function(
             enclave,
             remoteattestation_fcn_id_get_remote_report_with_pubkey,
             _input_buffer,
             _input_buffer_size,
             _output_buffer,
             _output_buffer_size,
             &_output_bytes_written)) != OE_OK)
        goto done;

    /* Setup output arg struct pointer. */
    _pargs_out = (get_remote_report_with_pubkey_args_t*)_output_buffer;
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));
    
    /* Check if the call succeeded. */
    if ((_result = _pargs_out->_result) != OE_OK)
        goto done;
    
    /* Currently exactly _output_buffer_size bytes must be written. */
    if (_output_bytes_written != _output_buffer_size)
    {
        _result = OE_FAILURE;
        goto done;
    }
    
    /* Unmarshal return value and out, in-out parameters. */
    *_retval = _pargs_out->_retval;
    /* No pointers to restore for deep copy. */
    OE_READ_OUT_PARAM(pem_key, (size_t)(sizeof(uint8_t*)));
    OE_READ_OUT_PARAM(key_size, (size_t)(sizeof(size_t)));
    OE_READ_OUT_PARAM(remote_report, (size_t)(sizeof(uint8_t*)));
    OE_READ_OUT_PARAM(remote_report_size, (size_t)(sizeof(size_t)));

    _result = OE_OK;

done:
    if (_buffer)
        free(_buffer);

    /* No `_ptrs` to free for deep copy. */

    return _result;
}

/**** OCALL functions. ****/

/* There were no ocalls. */
/**** OCALL function table. ****/

static oe_ocall_func_t __remoteattestation_ocall_function_table[] = {
    
    NULL
};

oe_result_t oe_create_remoteattestation_enclave(
    const char* path,
    oe_enclave_type_t type,
    uint32_t flags,
    const oe_enclave_setting_t* settings,
    uint32_t setting_count,
    oe_enclave_t** enclave)
{
    return oe_create_enclave(
               path,
               type,
               flags,
               settings,
               setting_count,
               __remoteattestation_ocall_function_table,
               0,
               enclave);
}

OE_EXTERNC_END
