/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#include "remoteattestation_t.h"

#include <openenclave/edger8r/enclave.h>

OE_EXTERNC_BEGIN

/**** ECALL functions. ****/

static void ecall_get_remote_report_with_pubkey(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    get_remote_report_with_pubkey_args_t* pargs_in = (get_remote_report_with_pubkey_args_t*)input_buffer;
    get_remote_report_with_pubkey_args_t* pargs_out = (get_remote_report_with_pubkey_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave. */
    /* oe_is_within_enclave explicitly checks if buffers are null or not. */
    if (!oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    /* There were no in nor in-out parameters. */

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    if (pargs_in->pem_key)
        OE_SET_OUT_POINTER(pem_key, sizeof(uint8_t*), uint8_t**);
    if (pargs_in->key_size)
        OE_SET_OUT_POINTER(key_size, sizeof(size_t), size_t*);
    if (pargs_in->remote_report)
        OE_SET_OUT_POINTER(remote_report, sizeof(uint8_t*), uint8_t**);
    if (pargs_in->remote_report_size)
        OE_SET_OUT_POINTER(remote_report_size, sizeof(size_t), size_t*);

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    pargs_out->_retval = get_remote_report_with_pubkey(
        pargs_in->pem_key,
        pargs_in->key_size,
        pargs_in->remote_report,
        pargs_in->remote_report_size);

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (output_buffer_size >= sizeof(*pargs_out) &&
        oe_is_within_enclave(pargs_out, output_buffer_size))
        pargs_out->_result = _result;
}

/**** ECALL function table. ****/

oe_ecall_func_t __oe_ecalls_table[] = {
    (oe_ecall_func_t) ecall_get_remote_report_with_pubkey
};

size_t __oe_ecalls_table_size = OE_COUNTOF(__oe_ecalls_table);

/**** OCALL function wrappers. ****/

/* There were no ocalls. */
OE_EXTERNC_END
